//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kms.Cloud.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.RegionSubdivision = new HashSet<RegionSubdivision>();
        }
    
        public long Id { get; set; }
        public string IsoCode { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<RegionSubdivision> RegionSubdivision { get; set; }
    }
}
