//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kms.Cloud.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionSubdivision
    {
        public RegionSubdivision()
        {
            this.RegionParticular = new HashSet<RegionParticular>();
        }
    
        public long Id { get; set; }
        public string IsoCode { get; set; }
        public string Name { get; set; }
        public short UtcOffset { get; set; }
    
        public virtual Region Region { get; set; }
        public virtual ICollection<RegionParticular> RegionParticular { get; set; }
    }
}
