//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kms.Cloud.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardGlobalization : IGlobalization
    {
        public string Title { get; set; }
        public string Text { get; set; }
        public string Source { get; set; }
    
        public virtual Reward Reward { get; set; }
    }
}
