//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kms.Cloud.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardSponsor : IPicture
    {
        public RewardSponsor()
        {
            this.Reward = new HashSet<Reward>();
        }
    
        public string Name { get; set; }
        public string WebsiteUri { get; set; }
    
        public virtual ICollection<Reward> Reward { get; set; }
    }
}
