//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kms.Cloud.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public Token()
        {
            this.WebAutoLoginToken = new HashSet<WebAutoLoginToken>();
        }
    
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public System.Guid Guid { get; set; }
        public System.Guid Secret { get; set; }
        public System.DateTime LastUseDate { get; set; }
        public byte LoginAttempts { get; set; }
        public string CallbackUri { get; set; }
        public Nullable<System.Guid> VerificationCode { get; set; }
        public string IPAddress { get; set; }
    
        public virtual ApiKey ApiKey { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<WebAutoLoginToken> WebAutoLoginToken { get; set; }
    }
}
