//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kms.Cloud.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTipHistory
    {
        public System.Guid Guid { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> Favoriteddate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Tip Tip { get; set; }
    }
}
