//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kms.Cloud.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRewardGiftShippingStatus
    {
        public long Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string TrackingCode { get; set; }
        public string TrackingLink { get; set; }
    
        public virtual UserRewardGiftClaimed UserRewardGiftClaimed { get; set; }
    }
}
