//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kilometros_WebGlobalization.WebApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OverviewStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OverviewStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kilometros_WebGlobalization.WebApp.OverviewStrings", typeof(OverviewStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Graph.
        /// </summary>
        public static string ActivityGraph {
            get {
                return ResourceManager.GetString("ActivityGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2 - Carbon Dioxide.
        /// </summary>
        public static string Co2Alt {
            get {
                return ResourceManager.GetString("Co2Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equivalence.
        /// </summary>
        public static string Equivalence {
            get {
                return ResourceManager.GetString("Equivalence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kcal - Kilocalories.
        /// </summary>
        public static string KcalAlt {
            get {
                return ResourceManager.GetString("KcalAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 24hrs.
        /// </summary>
        public static string Last24hrsGraph {
            get {
                return ResourceManager.GetString("Last24hrsGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Graph.
        /// </summary>
        public static string MonthlyGraph {
            get {
                return ResourceManager.GetString("MonthlyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings.
        /// </summary>
        public static string Savings {
            get {
                return ResourceManager.GetString("Savings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash savings.
        /// </summary>
        public static string SavingsAlt {
            get {
                return ResourceManager.GetString("SavingsAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip of the Day.
        /// </summary>
        public static string TipOfTheDay {
            get {
                return ResourceManager.GetString("TipOfTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today sleep time.
        /// </summary>
        public static string TodaySleepTime {
            get {
                return ResourceManager.GetString("TodaySleepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traveled today.
        /// </summary>
        public static string TodayTraveled {
            get {
                return ResourceManager.GetString("TodayTraveled", resourceCulture);
            }
        }
    }
}
