//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kilometros_WebGlobalization.WebApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RewardsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RewardsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kilometros_WebGlobalization.WebApp.RewardsStrings", typeof(RewardsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Rewards.
        /// </summary>
        public static string FutureRewards {
            get {
                return ResourceManager.GetString("FutureRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Reward.
        /// </summary>
        public static string NextReward {
            get {
                return ResourceManager.GetString("NextReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked after.
        /// </summary>
        public static string UnlockedAfter {
            get {
                return ResourceManager.GetString("UnlockedAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked on {0}.
        /// </summary>
        public static string UnlockedOnDate {
            get {
                return ResourceManager.GetString("UnlockedOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked rewards.
        /// </summary>
        public static string UnlockedRewards {
            get {
                return ResourceManager.GetString("UnlockedRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reward will be unlocked once you reach {0} {1}.
        /// </summary>
        public static string YourRewardWillBeUnlockedAt {
            get {
                return ResourceManager.GetString("YourRewardWillBeUnlockedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve come along way so your next reward is just this far.
        /// </summary>
        public static string YouveComeALongWay {
            get {
                return ResourceManager.GetString("YouveComeALongWay", resourceCulture);
            }
        }
    }
}
