//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPicture
    {
        public System.Guid Guid { get; set; }
        public System.DateTime CreationDate { get; set; }
        public byte[] Picture { get; set; }
        public string PictureMimeType { get; set; }
        public string PictureExtension { get; set; }
    }
}
