//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainModelContainer : DbContext
    {
        public MainModelContainer()
            : base("name=MainModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> UserSet { get; set; }
        public DbSet<Token> TokenSet { get; set; }
        public DbSet<ApiKey> ApiKeySet { get; set; }
        public DbSet<Tip> TipSet { get; set; }
        public DbSet<MotionLevel> MotionLevelSet { get; set; }
        public DbSet<TipCategory> TipCategorySet { get; set; }
        public DbSet<TipCategoryGlobalization> TipCategoryGlobalizationSet { get; set; }
        public DbSet<TipGlobalization> TipGlobalizationSet { get; set; }
        public DbSet<Data> DataSet { get; set; }
        public DbSet<UserBody> UserBodySet { get; set; }
        public DbSet<MotionLevelGlobalization> MotionLevelGlobalizationSet { get; set; }
        public DbSet<Reward> RewardSet { get; set; }
        public DbSet<RewardGift> RewardGiftSet { get; set; }
        public DbSet<RewardGlobalization> RewardGlobalizationSet { get; set; }
        public DbSet<RewardGiftToken> RewardGiftTokenSet { get; set; }
        public DbSet<RewardRegionalization> RewardRegionalizationSet { get; set; }
        public DbSet<RewardGiftGlobalization> RewardGiftGlobalizationSet { get; set; }
        public DbSet<UserMotionLevelHistory> UserMotionLevelHistorySet { get; set; }
        public DbSet<UserEarnedReward> UserEarnedRewardSet { get; set; }
        public DbSet<ContactInfo> ContactInfoSet { get; set; }
        public DbSet<ShippingInformation> ShippingInformationSet { get; set; }
        public DbSet<RewardGiftImage> RewardGiftImageSet { get; set; }
        public DbSet<SocialIdentity> SocialIdentitySet { get; set; }
        public DbSet<Region> RegionSet { get; set; }
        public DbSet<RegionSubdivision> RegionSubdivisionSet { get; set; }
    }
}
