//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainModelContainer : DbContext
    {
        public MainModelContainer()
            : base("name=MainModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> UserSet { get; set; }
        public DbSet<Token> TokenSet { get; set; }
        public DbSet<ApiKey> ApiKeySet { get; set; }
        public DbSet<Tip> TipSet { get; set; }
        public DbSet<MotionLevel> MotionLevelSet { get; set; }
        public DbSet<Data> DataSet { get; set; }
        public DbSet<UserBody> UserBodySet { get; set; }
        public DbSet<Reward> RewardSet { get; set; }
        public DbSet<RewardGift> RewardGiftSet { get; set; }
        public DbSet<RewardRegionalization> RewardRegionalizationSet { get; set; }
        public DbSet<UserMotionLevelHistory> UserMotionLevelHistorySet { get; set; }
        public DbSet<UserEarnedReward> UserEarnedRewardSet { get; set; }
        public DbSet<ContactInfo> ContactInfoSet { get; set; }
        public DbSet<ShippingInformation> ShippingInformationSet { get; set; }
        public DbSet<Region> RegionSet { get; set; }
        public DbSet<RegionSubdivision> RegionSubdivisionSet { get; set; }
        public DbSet<UserTipHistory> UserTipHistorySet { get; set; }
        public DbSet<IGlobalization> IGlobalizationSet { get; set; }
        public DbSet<IPicture> IPictureSet { get; set; }
        public DbSet<UserRewardGiftShippingStatus> UserRewardGiftShippingStatusSet { get; set; }
        public DbSet<OAuthCredential> OAuthCredentialSet { get; set; }
        public DbSet<OAuthNonce> OAuthNonceSet { get; set; }
        public DbSet<UserDataHourlyDistance> UserDataHourlyDistance { get; set; }
        public DbSet<UserDataTotalDistance> UserDataTotalDistance { get; set; }
        public DbSet<UserFriend> UserFriendSet { get; set; }
    }
}
