//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainModelContainer : DbContext
    {
        public MainModelContainer()
            : base("name=MainModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Token> TokenSet { get; set; }
        public virtual DbSet<ApiKey> ApiKeySet { get; set; }
        public virtual DbSet<Tip> TipSet { get; set; }
        public virtual DbSet<MotionLevel> MotionLevelSet { get; set; }
        public virtual DbSet<Data> DataSet { get; set; }
        public virtual DbSet<UserBody> UserBodySet { get; set; }
        public virtual DbSet<RewardGift> RewardGiftSet { get; set; }
        public virtual DbSet<RewardRegionalization> RewardRegionalizationSet { get; set; }
        public virtual DbSet<UserMotionLevelHistory> UserMotionLevelHistorySet { get; set; }
        public virtual DbSet<UserEarnedReward> UserEarnedRewardSet { get; set; }
        public virtual DbSet<ContactInfo> ContactInfoSet { get; set; }
        public virtual DbSet<ShippingInformation> ShippingInformationSet { get; set; }
        public virtual DbSet<Region> RegionSet { get; set; }
        public virtual DbSet<RegionSubdivision> RegionSubdivisionSet { get; set; }
        public virtual DbSet<UserTipHistory> UserTipHistorySet { get; set; }
        public virtual DbSet<IGlobalization> IGlobalizationSet { get; set; }
        public virtual DbSet<IPicture> IPictureSet { get; set; }
        public virtual DbSet<UserRewardGiftShippingStatus> UserRewardGiftShippingStatusSet { get; set; }
        public virtual DbSet<OAuthCredential> OAuthCredentialSet { get; set; }
        public virtual DbSet<OAuthNonce> OAuthNonceSet { get; set; }
        public virtual DbSet<UserDataHourlyDistance> UserDataHourlyDistance { get; set; }
        public virtual DbSet<UserDataTotalDistance> UserDataTotalDistance { get; set; }
        public virtual DbSet<UserFriend> UserFriendSet { get; set; }
        public virtual DbSet<RegionParticular> RegionParticularSet { get; set; }
        public virtual DbSet<Notification> NotificationSet { get; set; }
    }
}
