//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotionLevel
    {
        public MotionLevel()
        {
            this.MotionLevelGlobalization = new HashSet<MotionLevelGlobalization>();
            this.UserMotionLevelHistory = new HashSet<UserMotionLevelHistory>();
            this.Tip = new HashSet<Tip>();
        }
    
        public System.Guid Guid { get; set; }
        public int DistanceThresholdStart { get; set; }
        public int DistanceThresholdEnd { get; set; }
        public short DaysThresholdStart { get; set; }
        public short DaysThresholdEnd { get; set; }
    
        public virtual ICollection<MotionLevelGlobalization> MotionLevelGlobalization { get; set; }
        public virtual ICollection<UserMotionLevelHistory> UserMotionLevelHistory { get; set; }
        public virtual ICollection<Tip> Tip { get; set; }
    }
}
