//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    
    public enum OAuthService : int
    {
        Facebook = 0,
        Twitter = 1,
        Fitbit = 2,
        NikePlus = 3
    }
}
