//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OAuthCredential
    {
        public OAuthCredential()
        {
            this.IsInvalid = false;
        }
    
        public long Id { get; set; }
        public OAuthService OAuthProvider { get; set; }
        public string Uid { get; set; }
        public string Token { get; set; }
        public string Secret { get; set; }
        public bool IsInvalid { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
