//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardGiftImage
    {
        public long Id { get; internal set; }
        public System.DateTime CreationDate { get; internal set; }
        public byte[] Image { get; set; }
        public string ImageMimeType { get; set; }
    
        public virtual RewardGift RewardGift { get; set; }
    }
}
