//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardGift
    {
        public RewardGift()
        {
            this.IsShipped = false;
            this.RewardGiftGlobalization = new HashSet<RewardGiftGlobalization>();
            this.UserRewardGiftClaimed = new HashSet<UserRewardGiftClaimed>();
            this.RewardGiftPictures = new HashSet<RewardGiftPicture>();
        }
    
        public System.Guid Guid { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsShipped { get; set; }
    
        public virtual Reward Reward { get; set; }
        public virtual ICollection<RewardGiftGlobalization> RewardGiftGlobalization { get; set; }
        public virtual ICollection<UserRewardGiftClaimed> UserRewardGiftClaimed { get; set; }
        public virtual ICollection<RewardGiftPicture> RewardGiftPictures { get; set; }
    }
}
