//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reward
    {
        public Reward()
        {
            this.RewardGlobalization = new HashSet<RewardGlobalization>();
            this.RewardRegionalization = new HashSet<RewardRegionalization>();
        }
    
        public System.Guid Guid { get; set; }
        public string DistanceTrigger { get; set; }
        public string DaysTrigger { get; set; }
        public string Source { get; set; }
    
        public virtual RewardGift RewardGift { get; set; }
        public virtual ICollection<RewardGlobalization> RewardGlobalization { get; set; }
        public virtual ICollection<RewardRegionalization> RewardRegionalization { get; set; }
        public virtual UserEarnedReward UserEarnedReward { get; set; }
    }
}
