//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialIdentity
    {
        public SocialIdentity()
        {
            this.FacebookTokenIsInvalid = false;
            this.TwitterTokenIsInvalid = false;
        }
    
        public System.Guid Guid { get; set; }
        public string FacebookUid { get; set; }
        public string FacebookToken { get; set; }
        public bool FacebookTokenIsInvalid { get; set; }
        public string TwitterUid { get; set; }
        public string TwitterToken { get; set; }
        public string TwitterTokenSecret { get; set; }
        public bool TwitterTokenIsInvalid { get; set; }
    
        public virtual User User { get; set; }
    }
}
