//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipCategory
    {
        public TipCategory()
        {
            this.TipCategoryGlobalization = new HashSet<TipCategoryGlobalization>();
            this.Tip = new HashSet<Tip>();
        }
    
        public System.Guid Guid { get; set; }
        public byte[] Icon { get; set; }
        public string IconMimeType { get; set; }
    
        public virtual ICollection<TipCategoryGlobalization> TipCategoryGlobalization { get; set; }
        public virtual ICollection<Tip> Tip { get; set; }
    }
}
