//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipGlobalization
    {
        public long Id { get; internal set; }
        public string CultureCode { get; set; }
        public string Text { get; set; }
        public string Source { get; set; }
    
        public virtual Tip Tip { get; set; }
    }
}
