//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBody
    {
        public long Id { get; internal set; }
        public short Age { get; set; }
        public short Height { get; set; }
        public int Weight { get; set; }
        public string Sex { get; set; }
        public string StrideLengthWalking { get; set; }
        public string StrideLenghtRunning { get; set; }
        public System.DateTime LastEditDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
