//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDataTotalStepsView
    {
        public System.Guid User_Guid { get; set; }
        public short Activity { get; set; }
        public Nullable<int> TotalSteps { get; set; }
    }
}
