//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRewardGiftClaimed : IPicture
    {
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string RedeemCode { get; set; }
        public System.Data.Entity.Spatial.DbGeography ClaimLocation { get; set; }
    
        public virtual RewardGift RewardGift { get; set; }
        public virtual User RedeemedByUser { get; set; }
        public virtual UserRewardGiftShippingStatus ShippingStatus { get; set; }
    }
}
