//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFriend
    {
        public System.Guid Id { get; set; }
        public bool Accepted { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual User Friend { get; set; }
        public virtual User User { get; set; }
    }
}
