//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WristBand
    {
        public long Id { get; set; }
        public string ColorArgb { get; set; }
        public double Version { get; set; }
    
        public virtual WristBandUserOwnership WristBandUserOwnership { get; set; }
    }
}
