//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilometrosDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WristBandUserOwnership
    {
        public WristBandUserOwnership()
        {
            this.Data = new HashSet<Data>();
        }
    
        public long Id { get; set; }
        public System.DateTime AssociationDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Data> Data { get; set; }
        public virtual WristBand WristBand { get; set; }
    }
}
