//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kilometros_WebGlobalization.API {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControllerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControllerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kilometros_WebGlobalization.API.ControllerStrings", typeof(ControllerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops! We&apos;re still developing that one... sorry.
        /// </summary>
        public static string GenericNotImplemented {
            get {
                return ResourceManager.GetString("GenericNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already logged in.
        /// </summary>
        public static string Warning100_CannotLoginAgain {
            get {
                return ResourceManager.GetString("Warning100_CannotLoginAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User [{0}] requested could not be found, or password is incorrect.
        /// </summary>
        public static string Warning101_UserNotFound {
            get {
                return ResourceManager.GetString("Warning101_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token was deleted successfully.
        /// </summary>
        public static string Warning103_TokenDeleteOk {
            get {
                return ResourceManager.GetString("Warning103_TokenDeleteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth Request Token is invalid, expired or Verifier Code is invalid.
        /// </summary>
        public static string Warning104_RequestTokenInvalid {
            get {
                return ResourceManager.GetString("Warning104_RequestTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Network Token is invalid, expired or it has not been associated to any account.
        /// </summary>
        public static string Warning105_SocialTokenNotFound {
            get {
                return ResourceManager.GetString("Warning105_SocialTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth Request Token is required to engage in this resource&apos;s action.
        /// </summary>
        public static string Warning106_RequestTokenRequired {
            get {
                return ResourceManager.GetString("Warning106_RequestTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth Consumer Key does not have permission to access, modify or create this resource.
        /// </summary>
        public static string Warning107_ConsumerNotAllowed {
            get {
                return ResourceManager.GetString("Warning107_ConsumerNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth Request Token is no longer valid, use provided credentials as Access Token.
        /// </summary>
        public static string Warning108_RequestTokenExchanged {
            get {
                return ResourceManager.GetString("Warning108_RequestTokenExchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One account in this Social Network cannot have multiple accounts associated in KMS.
        /// </summary>
        public static string Warning109_SocialTokenAlreadyInUse {
            get {
                return ResourceManager.GetString("Warning109_SocialTokenAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is logged in and cannot register a new account.
        /// </summary>
        public static string Warning201_CannotCreateUserWithSessionOpen {
            get {
                return ResourceManager.GetString("Warning201_CannotCreateUserWithSessionOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information is not set yet.
        /// </summary>
        public static string Warning203_ContactInfoNotSet {
            get {
                return ResourceManager.GetString("Warning203_ContactInfoNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Profile is not set yet.
        /// </summary>
        public static string Warning204_PhysicalInfoNotSet {
            get {
                return ResourceManager.GetString("Warning204_PhysicalInfoNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Information is not set yet.
        /// </summary>
        public static string Warning205_ShippingInfoNotSet {
            get {
                return ResourceManager.GetString("Warning205_ShippingInfoNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another User using provided email.
        /// </summary>
        public static string Warning206_CannotCreateUserWithEmail {
            get {
                return ResourceManager.GetString("Warning206_CannotCreateUserWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity requested is invalid.
        /// </summary>
        public static string Warning301_ActivityInvalid {
            get {
                return ResourceManager.GetString("Warning301_ActivityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already Data with provided Timestamp.
        /// </summary>
        public static string Warning302_DataTimestampTooOld {
            get {
                return ResourceManager.GetString("Warning302_DataTimestampTooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User requested could not be found.
        /// </summary>
        public static string Warning401_FriendNotFound {
            get {
                return ResourceManager.GetString("Warning401_FriendNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendship with requested User already exists.
        /// </summary>
        public static string Warning402_FriendshipAlreadyExists {
            get {
                return ResourceManager.GetString("Warning402_FriendshipAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendship Request could not be found.
        /// </summary>
        public static string Warning403_FriendshipRequestNotFound {
            get {
                return ResourceManager.GetString("Warning403_FriendshipRequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Data received is invalid.
        /// </summary>
        public static string Warning501_AccountDataInvalid {
            get {
                return ResourceManager.GetString("Warning501_AccountDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Data received is not different to current data.
        /// </summary>
        public static string Warning502_AccountDataNotChanged {
            get {
                return ResourceManager.GetString("Warning502_AccountDataNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource requested could not be found..
        /// </summary>
        public static string Warning601_ResourceNotFound {
            get {
                return ResourceManager.GetString("Warning601_ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift requested could not be found, or ID is invalid.
        /// </summary>
        public static string Warning701_GiftNotFound {
            get {
                return ResourceManager.GetString("Warning701_GiftNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift requested is out of stock.
        /// </summary>
        public static string Warning702_GiftOutOfStock {
            get {
                return ResourceManager.GetString("Warning702_GiftOutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift has been claimed, and will be shipped soon.
        /// </summary>
        public static string Warning703_GiftShippingPending {
            get {
                return ResourceManager.GetString("Warning703_GiftShippingPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip requested could not be found, or ID is invalid.
        /// </summary>
        public static string Warning801_TipNotFound {
            get {
                return ResourceManager.GetString("Warning801_TipNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward requested could not be found, or ID is invalid.
        /// </summary>
        public static string Warning901_RewardNotFound {
            get {
                return ResourceManager.GetString("Warning901_RewardNotFound", resourceCulture);
            }
        }
    }
}
